# Generated by Django 6.0.6 on 2026-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatsession_options_searchanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='New Chat', max_length=200),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
