# Generated by Django 6.0.6 on 2026-07-14 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_context_chatsession_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('thumbs_up', 'Thumbs Up'), ('thumbs_down', 'Thumbs Down')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chatbot.chatmessage')),
            ],
            options={
                'unique_together': {('message', 'rating')},
            },
        ),
    ]
