# Generated by Django 6.0.6 on 2026-07-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI Payment'), ('CARD', 'Credit Card'), ('DEBIT', 'Debit Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet'), ('RAZORPAY', 'Razorpay')], max_length=20),
        ),
    ]
