# Generated by Django 6.0.5 on 2026-06-30 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Mobile', 'Mobile'), ('Headphone', 'Headphone'), ('Smartwatch', 'Smartwatch')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ram', models.CharField(blank=True, help_text='e.g. 8GB, 16GB', max_length=50)),
                ('storage', models.CharField(blank=True, help_text='e.g. 256GB SSD, 128GB', max_length=50)),
                ('processor', models.CharField(blank=True, help_text='e.g. Intel i5, Snapdragon 8', max_length=200)),
                ('battery', models.CharField(blank=True, help_text='e.g. 5000mAh', max_length=100)),
                ('display', models.CharField(blank=True, help_text='e.g. 6.5" AMOLED', max_length=200)),
                ('camera', models.CharField(blank=True, help_text='e.g. 48MP + 12MP', max_length=200)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('features', models.TextField(blank=True, help_text='Comma-separated features')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
